export enum Theme {
    DEFAULT = "default",
    CERULEAN = "cerulean",
    COSMO = "cosmo",
    CYBORG = "cyborg",
    DARKLY = "darkly",
    FLATLY = "flatly",
    JOURNAL = "journal",
    LITERA = "litera",
    LUMEN = "lumen",
    LUX = "lux",
    MATERIA = "materia",
    MINTY = "minty",
    PULSE = "pulse",
    SANDSTONE = "sandstone",
    SIMPLEX = "simplex",
    SKETCHY = "sketchy",
    SLATE = "slate",
    SOLAR = "solar",
    SPACELAB = "spacelab",
    SUPERHERO = "superhero",
    UNITED = "united",
    YETI = "yeti",
}
