export enum GameConstantKey {
    ATTACK_RATE_RANDOM_MAX = 'ATTACK_RATE_RANDOM_MAX',
    ATTACK_RATE_RANDOM_MIN = 'ATTACK_RATE_RANDOM_MIN',
    ENEMY_ATTACK_RATE_ARTS = 'ENEMY_ATTACK_RATE_ARTS',
    ENEMY_ATTACK_RATE_BUSTER = 'ENEMY_ATTACK_RATE_BUSTER',
    ENEMY_ATTACK_RATE_QUICK = 'ENEMY_ATTACK_RATE_QUICK',
}

type GameConstants = {
    [key in GameConstantKey]?: number
}

export default GameConstants;
