export enum CombineCalc {
    ADDITION = "addition",
    MULTIPLICATION = "multiplication",
    FIXED_VALUE = "fixedValue",
}

export enum CombineAdjustTarget {
    COMBINE_QP = "combineQp",
    COMBINE_EXP = "combineExp",
    ACTIVE_SKILL = "activeSkill",
    LARGE_SUCCESS = "largeSuccess",
    SUPER_SUCCESS = "superSuccess",
    LIMIT_QP = "limitQp",
    LIMIT_ITEM = "limitItem",
    SKILL_QP = "skillQp",
    SKILL_ITEM = "skillItem",
    TREASURE_DEVICE_QP = "treasureDeviceQp",
    TREASURE_DEVICE_ITEM = "treasureDeviceItem",
    QUEST_AP = "questAp",
    QUEST_EXP = "questExp",
    QUEST_QP = "questQp",
    QUEST_DROP = "questDrop",
    SVTEQUIP_COMBINE_QP = "svtequipCombineQp",
    SVTEQUIP_COMBINE_EXP = "svtequipCombineExp",
    SVTEQUIP_LARGE_SUCCESS = "svtequipLargeSuccess",
    SVTEQUIP_SUPER_SUCCESS = "svtequipSuperSuccess",
    QUEST_EVENT_POINT = "questEventPoint",
    ENEMY_SVT_CLASS_PICK_UP = "enemySvtClassPickUp",
    EVENT_EACH_DROP_NUM = "eventEachDropNum",
    EVENT_EACH_DROP_RATE = "eventEachDropRate",
    QUEST_FP = "questFp",
    QUEST_AP_FIRST_TIME = "questApFirstTime",
    DAILY_DROP_UP = "dailyDropUp",
    EXCHANGE_SVT_COMBINE_EXP = "exchangeSvtCombineExp",
    QUEST_USE_CONTINUE_ITEM = "questUseContinueItem",
    FRIEND_POINT_GACHA_FREE_DRAW_NUM = "friendPointGachaFreeDrawNum",
    QUEST_USE_FRIENDSHIP_UP_ITEM = "questUseFriendshipUpItem",
    QUEST_FRIENDSHIP = "questFriendship",
    LARGE_SUCCESS_BY_CLASS = "largeSuccessByClass",
    SUPER_SUCCESS_BY_CLASS = "superSuccessByClass",
    EXCHANGE_SVT = "exchangeSvt",
    QUEST_ITEM_FIRST_TIME = "questItemFirstTime",
}
