const TraitOverrideNames = new Map<number, string>([
    [1, "Gender:Male"],
    [2, "Gender:Female"],
    [3, "Gender:Unknown"],
    [100, "Class:Saber"],
    [101, "Class:Lancer"],
    [102, "Class:Archer"],
    [103, "Class:Rider"],
    [104, "Class:Caster"],
    [105, "Class:Assassin"],
    [106, "Class:Berserker"],
    [107, "Class:Shielder"],
    [108, "Class:Ruler"],
    [109, "Class:Alter Ego"],
    [110, "Class:Avenger"],
    [111, "Demon Pillar"],
    [112, "Class:Grand Caster"],
    [113, "Beast I"],
    [114, "Beast II"],
    [115, "Class:Moon Cancer"],
    [116, "Beast IIIR"],
    [117, "Class:Foreigner"],
    [118, "Beast IIIL"],
    [119, "Beast Unknown"],
    [120, "Class:Pretender"],
    [200, "Attribute:Sky"],
    [201, "Attribute:Earth"],
    [202, "Attribute:Human"],
    [203, "Attribute:Star"],
    [204, "Attribute:Beast"],
    [300, "Alignment:Lawful"],
    [301, "Alignment:Chaotic"],
    [302, "Alignment:Neutral"],
    [303, "Alignment:Good"],
    [304, "Alignment:Evil"],
    [305, "Alignment:Balanced"],
    [306, "Alignment:Madness"],
    [308, "Alignment:Summer"],
    [2386, "Kingprotea:Proliferation"],
    [2387, "Kingprotea:Growth"],
    [2664, "Kingprotea:Proliferation NP Defense"],
    [4001, "Card:Arts"],
    [4002, "Card:Buster"],
    [4003, "Card:Quick"],
    [4004, "Card:Extra"],
    [4008, "Player Card"],
    [4100, "Critical Hit"],
    [4101, "AOE NP"],
]);

export default TraitOverrideNames as ReadonlyMap<number, string>;
